# Generated by Django 3.1.7 on 2021-07-01 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210401_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Author_Profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
