# Generated by Django 3.1.7 on 2021-12-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Liked_posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='main.post'),
        ),
    ]
