# Generated by Django 3.1.7 on 2021-12-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211203_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='psts', to='main.Post'),
        ),
    ]
