# Generated by Django 3.1.7 on 2021-12-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Req_User_Follows_Author',
            field=models.BooleanField(default=False),
        ),
    ]
