# Generated by Django 3.1.7 on 2021-12-11 20:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_req_user_follows_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Author_Profile_Picture',
            field=models.CharField(default=uuid.uuid1, max_length=300),
        ),
    ]
