# Generated by Django 3.1.7 on 2021-12-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author_Profile_Picture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
