# Generated by Django 3.1.7 on 2021-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211211_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Cover_Picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
