# Generated by Django 3.1.7 on 2022-01-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_profile_picture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
