# Generated by Django 3.1.7 on 2022-01-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_message_sender_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_profile_picture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
