# Generated by Django 3.1.7 on 2022-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_notification_sender_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Display_Name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
