# Generated by Django 3.1.7 on 2022-01-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Author_Display_Name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
