# Generated by Django 3.1.7 on 2022-01-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_post_author_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
