# Generated by Django 3.1.7 on 2022-01-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220105_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
