# Generated by Django 3.1.7 on 2022-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_notification_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_shared_post',
            field=models.BooleanField(default=False),
        ),
    ]
