# Generated by Django 4.0.2 on 2022-02-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_message_is_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ImageString',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
