# Generated by Django 4.0.2 on 2022-02-08 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_post_imagestring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ImageString',
            field=models.CharField(default=uuid.uuid1, max_length=300),
        ),
    ]
