# Generated by Django 4.0.2 on 2022-02-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_post_imagestring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ImageString',
            field=models.CharField(default='', max_length=300),
        ),
    ]
