# Generated by Django 4.0.2 on 2022-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_post_imagestring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='UserHasLiked',
            field=models.BooleanField(default=False),
        ),
    ]
