# Generated by Django 4.0.2 on 2022-02-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_post_userhasliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='IsLike',
            field=models.BooleanField(default=False),
        ),
    ]
