# Generated by Django 4.0.2 on 2022-02-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_message_post_message_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
