# Generated by Django 4.0.2 on 2022-03-04 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0030_meme_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Caption',
            field=models.CharField(default=uuid.uuid1, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='IsOriginalpost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='IsQuotepost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='PostComments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcomment', to='main.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='PostItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='main.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='ReplyingTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repto', to=settings.AUTH_USER_MODEL),
        ),
    ]
