# Generated by Django 4.0.2 on 2022-03-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_post_image2_post_image3_post_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='IsComment',
            field=models.BooleanField(default=False),
        ),
    ]
