# Generated by Django 4.0.2 on 2022-03-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_post_iscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='InteractionID',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
