# Generated by Django 4.0.2 on 2022-03-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_post_interactionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Followee_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='folr', to='main.Follower_Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Following',
            field=models.ManyToManyField(blank=True, null=True, related_name='folw', to='main.Followee_Profile'),
        ),
    ]
