# Generated by Django 4.0.2 on 2022-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_follower_profile_followee_profile_profile_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='folr', to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Following',
            field=models.ManyToManyField(blank=True, null=True, related_name='folw', to='main.Profile'),
        ),
    ]
