# Generated by Django 4.0.2 on 2022-03-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='folr', to='main.Follower_Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Following',
            field=models.ManyToManyField(blank=True, null=True, related_name='folw', to='main.Followee_Profile'),
        ),
    ]
