# Generated by Django 4.0.2 on 2022-03-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followee_Profile',
            new_name='Following_Profile',
        ),
    ]
