# Generated by Django 4.0.2 on 2022-03-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_followee_profile_following_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Following',
        ),
        migrations.DeleteModel(
            name='Follower_Profile',
        ),
        migrations.DeleteModel(
            name='Following_Profile',
        ),
    ]
