# Generated by Django 4.0.2 on 2022-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Liked_posts',
        ),
        migrations.AddField(
            model_name='profile',
            name='Liked_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to='main.Post'),
        ),
    ]
